### ISSUE TITLE
Error while loading an entire class C addresses space

### ISSUE THREAD

**Issue by Hax0rG1rl** [marco-lancini/goscan#11]
Hi, 

Hi, thanks for your work. 

Got an issue here where I tried to load an entire class C space addresses from a text file. 

**OS Used:** Kali Linux

The format of that text file is: 

```
192.10x.x.0
...
...
192.10x.x.255
```

The error message is: 

```
[goscan] > load target MULTI targets.lst
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x830adb7]

goroutine 1 [running]:
github.com/marco-lancini/goscan/core/cli.cmdLoad(0x1aa12028, 0x3, 0x3, 0x4)
	/go/src/github.com/marco-lancini/goscan/core/cli/executor.go:137 +0xe7
github.com/marco-lancini/goscan/core/cli.Executor(0x1aa681e0, 0x51)
	/go/src/github.com/marco-lancini/goscan/core/cli/executor.go:23 +0x113
github.com/marco-lancini/goscan/vendor/github.com/c-bata/go-prompt.(*Prompt).Run(0x1aa85da0)
	/go/src/github.com/marco-lancini/goscan/vendor/github.com/c-bata/go-prompt/prompt.go:77 +0x548
main.main()
	/go/src/github.com/marco-lancini/goscan/main.go:67 +0xd2
```

Any ideas? thanks!

**Comment by marco-lancini** [comment]
Hi @Hax0rG1rl,
can you please try to provide the full path of your source file?

**Comment by Hax0rG1rl** [comment]
Right, so I know where the problem was. I tried to load the targets from a file outside of the current container which made the current framework logic to go nuts.
